require: rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Rails:
  Enabled: true

RSpec/NestedGroups:
  MaxNesting: 4
